### ISSUE TITLE
[QUESTION] Completely lost.

### ISSUE THREAD

**Issue by Warentan** [mrquantumoff/mcmodpackmanager_reborn#10]
There is no info on formatting or general use when it comes to modpacks. Is the import tab used for URLs? Files? Does it work for curseforge URLs? Modrinth? There is no notations or hints anywhere as to what to do when you want to install or download a modpack. Can you even import OTHER modpacks or can you only make your own? Whenever I try to download anything in any way, via file or link, it always just says "Invalid Data."

Downloading MODS doesnt even work, because it claims a "Missing Modpack," even though I'm not trying to do anything with a modpack.

This is more of a tool to MAKE modpacks, than a modpack manager.

**Comment by mrquantumoff** [comment]
The import tab is used both for base64 encoded modpacks exported from Quadrant, and for modpacks that were exported to a file. CurseForge and Modrinth  modpacks are not supported. They usually modify Minecraft's settings, because of that, the app would need to either completely overwrite the settings, or create a totally new .minecraft folder with everything required to run Minecraft. If you're looking for the ability to install modpacks from Modrinth or CurseForge, you should use something like Prism or GDLauncher.

**Comment by mrquantumoff** [comment]
If you have any further questions I'll be happy to answer them for you.

**Comment by mrquantumoff** [comment]
You must select a modpack in order to download a mod.
