### ISSUE TITLE
[FEATURE REQUEST] Add support for exporting and importing modpacks

### ISSUE THREAD

**Issue by rosset-nocpes** [mrquantumoff/mcmodpackmanager_reborn#6]
I wanted to be able to share my modpacks with my friends.
For example: when you made a Minecraft server with mods, so you can share a modpack that you can play with.

**Comment by mrquantumoff** [comment]
I was actually planning something like this for 10.0, now that someone is asking for it, I'll start working on implementing it.

**Comment by mrquantumoff** [comment]
I have a question regarding UX though, what is more comfortable for you as a user

1) Having to share your modConfig.json (from your modpack's folder)
2) Having to share a *possibly* long base64 string of your modConfig.json
3) Having to share a 7 digit code with your friends (but the app will connect to my proprietary api in order to do that)

**Comment by mrquantumoff** [comment]
Please vote using my [mastodon](https://mastodon.social/@mrquantumoff/110589647057215067) page.

**Comment by mrquantumoff** [comment]
I have added this feature. Now every mod downloaded with Minecraft Modpack Manager v10+ is indexed in a modConfig.json file, which can be easily imported/exported from the application. However, sadly there are a few limits to this. 

* If you want to add a custom mod you'll have to add it manually through the json file, by adding a new entry to the mods array which should look like this
```json
{
"id": "anything",
"downloadUrl" :"example.com/mymod.jar",
"source": "anything, but ModSource.online is recommended"
}
```
* You'll probably have to redownload all the mods you have (I can't really do anything about it, since your mods weren't indexed before)
